### PR TITLE
Add Virtualenv support to the WSGI file.

### PR DESCRIPTION
**Pull request by rotated8**
The path to the activate_this.py file will need to be changed during deployment.

### CODE REVIEW

**Comment by rotated8** [comment]
Should the Apache config be part of this, or a separate PR?

**Comment by yinlinchen** [comment]
Yes,  https://webapps-pprd.es.vt.edu/jira/browse/LIBFT-10 .

**Comment by rotated8** [comment]
@yinlinchen Add any update you want for the README, and this is ready to merge.

**Comment by yinlinchen** [comment]
Please put fishtraits.conf in config/Apache/

**Comment by rotated8** [comment]
There will only be one config file.

**Comment by rotated8** [comment]
Fixes JIRA LIBFT-10

**Pull request merged**
